[package]
name = 'propertize'
version = '0.0.0'

[addresses]
propertize_addr = '88f1f347355690fd5aabd1821b3763434b8c88af51c65cd30b4c9e8028fe79c7'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-token-objects'